(()=>{'use strict';
const B=window.APLUS_BANK.questions,M=window.APLUS_BANK.metadata,$=id=>document.getElementById(id),P='aplus-progress',S='aplus-session';
const e={tabs:[...document.querySelectorAll('.tab')],views:[...document.querySelectorAll('.view')],launcher:$('launcher'),form:$('launchForm'),exam:$('examSelect'),len:$('lengthSelect'),mode:$('modeSelect'),domain:$('domainSelect'),weak:$('weakOnly'),timerOn:$('timerToggle'),cont:$('continueBtn'),note:$('weightNote'),quiz:$('quiz'),results:$('results'),counter:$('questionCounter'),timer:$('timer'),bar:$('progressBar'),examBadge:$('examBadge'),domainBadge:$('domainBadge'),objBadge:$('objectiveBadge'),qtype:$('questionType'),flag:$('flagBtn'),prompt:$('questionPrompt'),area:$('answerArea'),msg:$('validationMsg'),fb:$('feedback'),check:$('submitAnswerBtn'),next:$('nextBtn'),quit:$('quitBtn'),title:$('resultTitle'),pct:$('scorePct'),summary:$('scoreSummary'),breakdown:$('domainBreakdown'),reviewBtn:$('reviewMissedBtn'),newBtn:$('newSessionBtn'),review:$('reviewList'),pSummary:$('progressSummary'),pDomains:$('progressDomains'),reset:$('resetProgressBtn'),theme:$('themeToggle')};
const load=(k,f)=>{try{let x=localStorage.getItem(k);return x?JSON.parse(x):f}catch{return f}},save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch{}},esc=s=>String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c])),shuffle=a=>{a=[...a];for(let i=a.length-1;i;i--){let j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
let progress=load(P,{totalAnswered:0,totalCorrect:0,byDomain:{},missedIds:[]}),session=null,timerId=null;
function setTheme(t){document.documentElement.dataset.theme=t;e.theme.textContent=t==='dark'?'Light mode':'Dark mode';localStorage.setItem('aplus-theme',t)}setTheme(localStorage.getItem('aplus-theme')||'light');e.theme.onclick=()=>setTheme(document.documentElement.dataset.theme==='dark'?'light':'dark');
e.tabs.forEach(t=>t.onclick=()=>{e.tabs.forEach(x=>x.classList.toggle('active',x===t));e.views.forEach(v=>v.hidden=v.id!==t.dataset.view+'View');if(t.dataset.view==='progress')renderProgress()});
const domains=x=>x==='mixed'?[...M.domains['1201'],...M.domains['1202']]:M.domains[x];
function refresh(){let ex=e.exam.value;e.domain.innerHTML='<option value="all">All domains — official weighting</option>'+domains(ex).map(d=>`<option value="${esc(d)}">${esc(d)}</option>`).join('');e.note.textContent=ex==='mixed'?'Mixed review draws from both current exams.':Object.entries(M.weights[ex]).map(([d,p])=>`${d} ${p}%`).join(' • ')}e.exam.onchange=refresh;refresh();
function stats(d){return progress.byDomain[d]||{answered:0,correct:0}}
function pick(ex,n,domain,weak){let pool=B.filter(q=>ex==='mixed'||q.exam===ex);if(domain!=='all')return shuffle(pool.filter(q=>q.domain===domain)).slice(0,n);let ds=domains(ex),w={};if(ex==='mixed')ds.forEach(d=>w[d]=1);else Object.assign(w,M.weights[ex]);if(weak)ds.forEach(d=>{let s=stats(d),a=s.answered?s.correct/s.answered:.5;w[d]*=1.2+(1-a)*1.8});let total=Object.values(w).reduce((a,b)=>a+b,0),out=[];ds.forEach(d=>{let count=Math.floor(n*w[d]/total);out.push(...shuffle(pool.filter(q=>q.domain===d)).slice(0,count))});while(out.length<n){let extra=shuffle(pool.filter(q=>!out.includes(q)))[0];if(!extra)break;out.push(extra)}return shuffle(out).slice(0,n)}
function saveSession(){if(session&&!session.finished)save(S,session)}function clearSession(){localStorage.removeItem(S)}
let old=load(S,null);if(old?.questions?.length){e.cont.hidden=false;e.cont.onclick=()=>{session=old;startUI()}}
e.form.onsubmit=ev=>{ev.preventDefault();let n=+e.len.value,ex=e.exam.value,q=pick(ex,n,e.domain.value,e.weak.checked);session={config:{ex,n,mode:e.mode.value},questions:q,index:0,responses:Array(q.length).fill(null),counted:Array(q.length).fill(false),flagged:[],remaining:e.timerOn.checked?n*60:null,finished:false};saveSession();startUI()};
function startUI(){e.launcher.hidden=true;e.results.hidden=true;e.quiz.hidden=false;renderQ();startTimer()}
function renderQ(){let q=session.questions[session.index],r=session.responses[session.index];e.counter.textContent=`Question ${session.index+1} of ${session.questions.length}`;e.bar.style.width=`${(session.index+1)/session.questions.length*100}%`;e.examBadge.textContent=q.exam==='1201'?'Core 1 — 220-1201':'Core 2 — 220-1202';e.domainBadge.textContent=q.domain;e.objBadge.textContent='Objective '+q.objective;e.qtype.textContent='Multiple choice';e.prompt.textContent=q.prompt;e.msg.textContent='';e.fb.hidden=true;e.fb.className='feedback';e.area.innerHTML='';e.flag.textContent=session.flagged.includes(q.id)?'★ Flagged':'☆ Flag';e.check.hidden=false;e.next.hidden=true;q.choices.forEach((c,i)=>{let l=document.createElement('label');l.className='answer-option';l.innerHTML=`<input type="radio" name="answer" value="${i}" ${r===i?'checked':''}><span><strong>${i+1}.</strong> ${esc(c)}</span>`;let inp=l.querySelector('input');if(inp.checked)l.classList.add('selected');inp.onchange=()=>{[...e.area.children].forEach(x=>x.classList.remove('selected'));l.classList.add('selected')};e.area.appendChild(l)});updateTimer()}
const response=()=>{let x=e.area.querySelector('input:checked');return x?+x.value:null},correct=(q,r)=>r===q.correct;
function record(q,ok,i){if(session.counted[i])return;progress.totalAnswered++;if(ok)progress.totalCorrect++;progress.byDomain[q.domain]||={answered:0,correct:0};progress.byDomain[q.domain].answered++;if(ok)progress.byDomain[q.domain].correct++;if(ok)progress.missedIds=progress.missedIds.filter(x=>x!==q.id);else if(!progress.missedIds.includes(q.id))progress.missedIds.push(q.id);session.counted[i]=true;save(P,progress)}
function feedback(q,r){let ok=correct(q,r);[...e.area.children].forEach((x,i)=>{if(i===q.correct)x.classList.add('correct');else if(i===r)x.classList.add('incorrect');x.querySelector('input').disabled=true});e.fb.hidden=false;e.fb.classList.add(ok?'good':'bad');e.fb.innerHTML=`<strong>${ok?'Correct.':'Not quite.'}</strong> ${esc(q.explanation)}${ok?'':`<div><strong>Correct:</strong> ${esc(q.choices[q.correct])}</div>`}`}
e.check.onclick=()=>{let q=session.questions[session.index],r=response();if(r===null){e.msg.textContent='Choose an answer before continuing.';return}session.responses[session.index]=r;if(session.config.mode==='study'){record(q,correct(q,r),session.index);feedback(q,r);e.check.hidden=true;e.next.hidden=false;saveSession()}else advance()};
function advance(){if(session.index===session.questions.length-1)finish();else{session.index++;saveSession();renderQ()}}e.next.onclick=advance;
e.flag.onclick=()=>{let id=session.questions[session.index].id,i=session.flagged.indexOf(id);i>=0?session.flagged.splice(i,1):session.flagged.push(id);saveSession();renderQ()};e.quit.onclick=()=>{if(confirm('End this session and score answered questions?'))finish(true)};
function finish(partial=false){stopTimer();if(session.config.mode==='exam')session.questions.forEach((q,i)=>{let r=session.responses[i];if(r!==null)record(q,correct(q,r),i)});session.finished=true;clearSession();e.quiz.hidden=true;e.results.hidden=false;renderResults(partial)}
function renderResults(partial){let ans=session.responses.map((r,i)=>({q:session.questions[i],r})).filter(x=>x.r!==null),good=ans.filter(x=>correct(x.q,x.r)).length,pct=ans.length?Math.round(good/ans.length*100):0;e.title.textContent=partial?'Partial session results':'Session results';e.pct.textContent=pct+'%';e.summary.textContent=`${good} correct out of ${ans.length} answered. ${pct>=85?'Strong practice result.':pct>=70?'Good progress; review misses next.':'Use the domain breakdown to target weak areas.'}`;let by={};ans.forEach(x=>{by[x.q.domain]||={a:0,c:0};by[x.q.domain].a++;if(correct(x.q,x.r))by[x.q.domain].c++});e.breakdown.innerHTML=Object.entries(by).map(([d,s])=>{let p=Math.round(s.c/s.a*100);return`<div class="domain-row"><strong>${esc(d)}</strong><div class="mini-track"><div class="mini-fill" style="width:${p}%"></div></div><span>${p}%</span></div>`}).join('');let missed=ans.filter(x=>!correct(x.q,x.r));e.reviewBtn.hidden=!missed.length;e.reviewBtn.onclick=()=>e.review.innerHTML=missed.map(({q,r})=>`<article class="review-item"><h3>${esc(q.prompt)}</h3><p><strong>Your answer:</strong> ${esc(q.choices[r])}</p><p class="answer-key"><strong>Correct:</strong> ${esc(q.choices[q.correct])}</p><p>${esc(q.explanation)}</p></article>`).join('')}
e.newBtn.onclick=()=>{session=null;e.results.hidden=true;e.launcher.hidden=false;e.review.innerHTML=''};
function startTimer(){if(timerId||session.remaining===null)return;timerId=setInterval(()=>{session.remaining=Math.max(0,session.remaining-1);updateTimer();if(session.remaining%10===0)saveSession();if(session.remaining===0){stopTimer();finish(true);alert('Time is up.')}},1000)}function stopTimer(){if(timerId){clearInterval(timerId);timerId=null}}function updateTimer(){if(session.remaining===null){e.timer.textContent='Untimed';return}let m=Math.floor(session.remaining/60),s=session.remaining%60;e.timer.textContent=`${m}:${String(s).padStart(2,'0')}`}
function renderProgress(){let acc=progress.totalAnswered?Math.round(progress.totalCorrect/progress.totalAnswered*100):0;e.pSummary.innerHTML=`<div class="stat"><strong>${progress.totalAnswered}</strong><span>questions answered</span></div><div class="stat"><strong>${acc}%</strong><span>overall accuracy</span></div><div class="stat"><strong>${progress.missedIds.length}</strong><span>missed queue</span></div>`;e.pDomains.innerHTML=[...M.domains['1201'],...M.domains['1202']].map(d=>{let s=stats(d),p=s.answered?Math.round(s.correct/s.answered*100):0;return`<div class="domain-row"><span><strong>${esc(d)}</strong><br><small>${s.answered} answered</small></span><div class="mini-track"><div class="mini-fill" style="width:${p}%"></div></div><span>${s.answered?p+'%':'—'}</span></div>`}).join('')}
e.reset.onclick=()=>{if(confirm('Delete all locally stored A+ practice history?')){progress={totalAnswered:0,totalCorrect:0,byDomain:{},missedIds:[]};save(P,progress);renderProgress()}};window.addEventListener('beforeunload',saveSession);
})();